### ISSUE TITLE
testing w/o interface

### ISSUE THREAD

**Issue by minano** [psi46/pxar#337] opened 2015-05-05 09:43 UTC
Trying the following command:

cat main/test | bin/pXar –d data/ModuleTest 
or
bin/pXar -d data/ModuleTest -t PixelAlive 
or 
bin/pXar -d data/ModuleTest

stop the running at that point:

[11:35:45.810]     INFO: *** Welcome to pxar ***
[11:35:45.814]     INFO: no rootlogon.C found, live with the defaults provided
[11:35:45.814]     INFO: pxar: reading config parameters from ./configParameters.dat
[11:35:45.814]     INFO: Can not open file './configParameters.dat' to read Config Parameters.

However, running pXar from terminal getting the interface (bin/pXar -d data/ModuleTest -g) is not giving any problem and the configParameters.dat can be read.
Do you know any possible reason for that?
Thanks!
Mercedes

**Comment by ursl** [comment] 2015-05-05 09:56
Hi Mercedes,

I cannot reproduce this:

marwees>bin/pXar -d data/ModuleTest
[11:51:39.341]     INFO: *** Welcome to pxar ***
# On branch master
# Changes not staged for commit:
#   (use "git add <file>..." to update what will be committed)
#   (use "git checkout -- <file>..." to discard changes in working
directory)
#
# modified:   main/pXar.cc
# modified:   tests/PixTestHighRate.cc
#
# Untracked files:
#   (use "git add <file>..." to include in what will be committed)
#
# ana/test.C
no changes added to commit (use "git add" and/or "git commit -a")
[11:51:39.361]     INFO: no rootlogon.C found, live with the defaults
provided
[11:51:39.361]     INFO: pxar: reading config parameters from
data/ModuleTest/configParameters.dat
[11:51:39.361]     INFO: pxar: dumping results into
data/ModuleTest/pxar.root logfile = data/ModuleTest/pxar.log
[11:51:39.361]     INFO: creating backup files for previous run:
data/ModuleTest/pxar_20150505_115134.root and
data/ModuleTest/pxar_20150505_115134.log
[11:51:39.378]     INFO: *** Welcome to pxar ***
[11:51:39.378]     INFO: *** Today: 2015/05/05


I would have no idea why this should be, in fact, as the printout

[11:53:30.125]     INFO: pxar: reading config parameters from
data/ModuleTest/configParameters.dat

comes before the GUI is instantiated or the decision between GUI running or
not has been taken.

Can you please make sure that you always use the same character '-' when
providing the option -d? From your message it is not obvious that it is a
minus sign always. If it is not a minus sign, then probably the option
parsing is not working.

Cheers,
--U.

​

**Comment by minano** [comment] 2015-05-05 10:05
I think it can come from the DTB more than pXar. Is it possible?
It is failing sometimes even adding -g
I will check with other DTB.

Cheers,
Mercedes

**Comment by minano** [comment] 2015-05-05 10:59
Thanks for the suggestion, the problem was the character '-'. 
1) cat main/test | bin/pXar –d data/ModuleTest
2) cat main/test | bin/pXar -d data/ModuleTest

1) generated with a script from other computer and 2) written by hand. 

Cheers,
Mercedes

**Closed** 2015-05-05 11:20 UTC
