### ISSUE TITLE
Number of ROCs (0) != Token Chain Length (1)

### ISSUE THREAD

**Issue by dinardo** [psi46/pxar#367] opened 2015-07-06 16:40 UTC
Dear Experts,
I compiled pXar under SLC 5.
I was also able to upgrade the firmware from 3.6 to 4.2
I'm able to run the GUI. I would like to make simple
calibrations of a single ROC module.

Here is the print out on screen when I run the GUI:
```
[15:49:48.087]     INFO: *** Welcome to pxar ***
# On branch master
#
# Initial commit
#
# Untracked files:
#   (use "git add <file>..." to include in what will be committed)
#
#.CERNAlerter/
#.ICEauthority
#.abrt/
#.bash_history
#.bash_logout
#.bash_profile
#.bashrc
#.cache/
#.config/
#.dbus/
#.emacs
#.esd_auth
#.gconf/
#.gconfd/
#.gitconfig
#.gnome2/
#.gnote/
#.gnupg/
#.gstreamer-0.10/
#.gtk-bookmarks
#.imsettings.log
#.local/
#.mozilla/
#.pulse-cookie
#.pulse/
#.root_hist
#.ssh/
#.thumbnails/
#.vboxclient-clipboard.pid
#.vboxclient-display.pid
#.vboxclient-draganddrop.pid
#.vboxclient-seamless.pid
#.xsession-errors
#.xsession-errors.old
#.zshrc
#Desktop/
#Downloads/
#Init.sh
#MountShareHost.sh
#cmake
#cmake-3.2.3-Linux-x86_64/
#confuse-2.7/
#libftdi1-1.2/
#pxar/
#roc/
#root
#root_v5_34_30/
nothing added to commit but untracked files present (use "git add" to track)
[15:49:48.093]     INFO: no rootlogon.C found, live with the defaults provided
[15:49:48.093]     INFO: pxar: reading config parameters from roc/configParameters.dat
[15:49:48.093]     INFO: pxar: dumping results into roc/pxar.root logfile = roc/pxar.log
[15:49:48.093]     INFO: creating backup files for previous run: roc/pxar_20150706_153419.root and roc/pxar_20150706_153419.log
[15:49:48.121]     INFO: *** Welcome to pxar ***
[15:49:48.121]     INFO: *** Today: 2015/07/06
[15:49:48.121]     INFO:       reading roc/dacParameters_C0.dat
[15:49:48.121]     INFO:       reading roc/defaultMaskFile.dat
[15:49:48.121]     INFO:       reading roc/trimParameters_C0.dat
[15:49:48.125]     INFO:       reading roc/tbParameters.dat
[15:49:48.125]     INFO:         clk: 4
[15:49:48.125]     INFO:         ctr: 4
[15:49:48.125]     INFO:         sda: 19
[15:49:48.125]     INFO:         tin: 9
[15:49:48.125]     INFO:         level: 15
[15:49:48.125]     INFO:         deser160phase: 4
[15:49:48.125]    QUIET: Instanciating API for pxar v2.2.4
[15:49:48.125]     INFO: Log level: INFO
[15:49:48.209]    QUIET: Connection to board DTB_WWV4F3 opened.
[15:49:48.234]     INFO: DTB startup information
--- DTB info------------------------------------------
Board id:    120
HW version:  DTB1.2
FW version:  4.2
SW version:  4.2
USB id:      DTB_WWV4F3
MAC address: 40D855118078
Hostname:    pixelDTB120
Comment:     
------------------------------------------------------
[15:49:48.287]     INFO: RPC call hashes of host and DTB match: 447413373
[15:49:49.749]     INFO: DUT info: 
[15:49:49.750]     INFO: The DUT currently contains the following objects:
[15:49:49.750]     INFO:  0 TBM Cores (0 ON)
[15:49:49.750]     INFO:  1 ROCs (1 ON) with 4160 pixelConfigs
[15:49:49.750]     INFO: ROC 0: 19 DACs set, Pixels: 0 masked, 0 active.
[15:49:50.355]     INFO:       reading roc/phCalibrationFitErr_C0.dat
[15:49:50.355]    ERROR: <ConfigParameters.cc/readGainPedestalParameters:L967> cannot open
roc/phCalibrationFitErr_C0.dat for reading PH calibration constants
[15:49:50.400]     INFO:       reading roc/readbackCal_C0.dat
[15:49:50.401]     INFO:       reading roc/phCalibrationFitErr_C0.dat
[15:49:50.401]    ERROR: <ConfigParameters.cc/readGainPedestalParameters:L967> cannot open
roc/phCalibrationFitErr_C0.dat for reading PH calibration constants
[15:49:50.436]     INFO:       reading roc/phCalibrationFitErr_C0.dat
[15:49:50.436]    ERROR: <ConfigParameters.cc/readGainPedestalParameters:L967> cannot open
roc/phCalibrationFitErr_C0.dat for reading PH calibration constants
```

When I try to run the pixel alive I get the following error many many times:
```
ERROR: <datapipe.cc/CheckEventValidity:L437> Number of ROCs (0) != Token Chain Length (1)
```

and the pixel-alive is empty.
Do you know what this is all about ?

Many thanks for your help.
Kind regards,
- Mauro.

**Comment by simonspa** [comment] 2015-07-06 17:39
With a confidence level of >95% the problem is not adjusted DTB timing settings. Whenever using a new DTB or a new configuration file set you first have to run the Setup tests which calibrates the clock and DESER160 phases to align with the ROC data. If this is out of phase, the `0x7f8` is not recognised because it's sampled as e.g. `0xffe` and thus results in no ROC header being detected.

**Comment by simonspa** [comment] 2015-07-06 17:40
addedum: this is also true for new firmwares, every firmware has some now FPGA-internal delays

**Comment by dinardo** [comment] 2015-07-06 20:22
Very well, Simonspa.
Many thanks.

I need just one last hint:
where can I find how to run the "Setup tests". I didn't find any trace on the twiki:
https://twiki.cern.ch/twiki/bin/view/CMS/Pxar

Many thanks,
- Mauro.

**Comment by simonspa** [comment] 2015-07-06 20:48
Hi @dinardo,

if you created the configuration files using the `mkConfig` script by @ursl then there should be a tab in the GUI called "Setup" which does exactly what you need. If not, add the followiung lines to your `testParameters.dat` file:

```
-- Setup
DeserMax            7
ClkMax              19
saveTbParameters    button
```

Cheers,
Simon

**Comment by dinardo** [comment] 2015-07-07 16:41
Hi Simonspa,
many thanks. It works!

I think I know how the PSI46dig works, since I've been working with PSI46ana.
But I would very much benefit from a first guide line on what is the sequence
of buttons to click, or settings to set in pXar, in order to perform a full PSI46dig
calibration. I know that there is a "full-test" macro, but I would like to know more
in detail what it does.

Basically I would like to know what is the sequence of tests to be performed in order
to get the final / best gain&pedestal calibration.

Many thanks.
- Mauro.

**Comment by simonspa** [comment] 2015-07-07 20:52
Well, I'm not the expert on this, but usually I do the tests
setup, pretest, pixelalive, bumbonding, trim, gainpedestal
in this order.

By the way: you can also test PSI46v2 (analog) using the DTB and pxar, the very only thing that you need to change is the roctype in the config file. :)

**Comment by simonspa** [comment] 2015-07-09 18:45
I guess we can close this issue since the initial problem is resolved.
If you need more documentation on test procedures I would recommend opening a new ticket for this.

Cheers,
Simon

**Closed by simonspa** 2015-07-09 18:45 UTC
